
export const BASE_URL = ''
export const CHECK_IS_AUTHENTICATED = 'CHECK_IS_AUTHENTICATED';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const GET_USER_DATA = 'GET_USER_DATA';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATED = 'AUTHENTICATED';
